spring.application.name=mini-project-BNI
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_project_bni
spring.datasource.username=postgres
spring.datasource.password=bejoO4000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true